### ISSUE TITLE
Cannot find module './lib/components'

### ISSUE THREAD

**Issue by t3db0t** [SC5/mozaik-ext-analytics#2]
Getting this while trying to build from scratch with Yeoman generator:

```
$ gulp build
(node:26683) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:26683) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[16:54:02] Using gulpfile ~/Projects/Mozaik/gulpfile.js
[16:54:02] Starting 'copy:fonts'...
[16:54:02] Copying fonts
[16:54:02] Starting 'copy:styles'...
[16:54:02] Copying styles
[16:54:02] Starting 'copy:imgs'...
[16:54:02] Copying images from extensions and themes
[16:54:02] Starting 'collect:styles'...
[16:54:02] Collecting extensions styles
[16:54:02] Finished 'collect:styles' after 8.84 ms
[16:54:02] Starting 'styles:dev'...
[16:54:02] Compiling stylus code using theme '/Users/tedhayes/Projects/Mozaik/node_modules/mozaik/src/themes/night-blue'
[16:54:02] Starting 'js'...
[16:54:02] Finished 'styles:dev' after 49 ms
[16:54:02] Starting 'styles'...
[16:54:02] Finished 'styles' after 4.71 μs
[16:54:02] Finished 'copy:imgs' after 65 ms
[16:54:03] Finished 'copy:styles' after 412 ms
[16:54:04] Finished 'copy:fonts' after 1.32 s
[16:54:04] Starting 'copy'...
[16:54:04] Finished 'copy' after 3.32 μs
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module './lib/components' from '/Users/.../Projects/Mozaik/node_modules/mozaik-ext-analytics'
    at /Users/.../Projects/Mozaik/node_modules/resolve/lib/async.js:55:21
    at load (/Users/.../Projects/Mozaik/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/.../Projects/Mozaik/node_modules/resolve/lib/async.js:92:31)
    at /Users/.../Projects/Mozaik/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by t3db0t** [comment]
FWIW, I commented out this line and it built:

```
// module.exports = require('./lib/components');
```

**Comment by juhamust** [comment]
This is no longer issue as no lib folder exists anymore.
